-- =============================================================================
-- FILE: sql/02_load_data.sql
-- PROJECT: Pymaceuticals Drug Efficacy Study
-- PURPOSE: Load CSVs into the database (PostgreSQL COPY syntax)
--          For SQLite / DuckDB, replace COPY with appropriate import commands.
-- =============================================================================

-- NOTE: Adjust file paths to match your environment.
--       For DuckDB: use read_csv_auto() — see comments below.
--       For SQLite: use .import command in the SQLite CLI.

-- -----------------------------------------------------------------------------
-- A. PostgreSQL COPY commands
-- -----------------------------------------------------------------------------

-- Load mouse metadata
COPY mouse_metadata (mouse_id, drug_regimen, sex, age_months, weight_g)
FROM '/path/to/data/raw/Mouse_metadata.csv'
WITH (FORMAT CSV, HEADER TRUE, DELIMITER ',', NULL '');

-- Load study results
COPY study_results (mouse_id, timepoint, tumor_volume_mm3, metastatic_sites)
FROM '/path/to/data/raw/Study_results.csv'
WITH (FORMAT CSV, HEADER TRUE, DELIMITER ',', NULL '');

-- Load mouse summary (generated by Python pipeline)
COPY mouse_summary (
    mouse_id, drug_regimen, sex, age_months, weight_g,
    total_timepoints, max_timepoint, initial_tumor_vol,
    final_tumor_vol, max_tumor_vol, min_tumor_vol, max_metastatic
)
FROM '/path/to/data/processed/mouse_summary.csv'
WITH (FORMAT CSV, HEADER TRUE, DELIMITER ',', NULL '');

LOAD DATA INFILE 'C:\Program Files\MySQL\MySQL Server 8.0\uploads\mouse_summary.csv'
INTO TABLE mouse_summary
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
    mouse_id, drug_regimen, sex, age_months, weight_g,
    total_timepoints, max_timepoint, initial_tumor_vol,
    final_tumor_vol, max_tumor_vol, min_tumor_vol, max_metastatic
);
SHOW VARIABLES LIKE 'secure_file_priv';

SET GLOBAL local_infile = 1;

LOAD DATA LOCAL INFILE 'C:\ZEEL\projects\pharma_project\data\processed\mouse_summary.csv'
INTO TABLE mouse_summary
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
    mouse_id, drug_regimen, sex, age_months, weight_g,
    total_timepoints, max_timepoint, initial_tumor_vol,
    final_tumor_vol, max_tumor_vol, min_tumor_vol, max_metastatic
);

-- -----------------------------------------------------------------------------
-- B. Populate derived columns after load
-- -----------------------------------------------------------------------------

-- Tumour volume change from baseline (45 mm³)
UPDATE study_results
SET
    tumor_vol_change_mm3 = ROUND(tumor_volume_mm3 - 45.0, 3),
    tumor_vol_change_pct = ROUND((tumor_volume_mm3 - 45.0) / 45.0 * 100.0, 3);

-- Weight category on mouse_metadata
UPDATE mouse_metadata
SET weight_category = CASE
    WHEN weight_g < 17  THEN 'Light (<17g)'
    WHEN weight_g <= 22 THEN 'Medium (17-22g)'
    ELSE                     'Heavy (>22g)'
END;

-- Age group on mouse_metadata
UPDATE mouse_metadata
SET age_group = CASE
    WHEN age_months <= 6  THEN '0-6 mo'
    WHEN age_months <= 12 THEN '7-12 mo'
    WHEN age_months <= 24 THEN '13-24 mo'
    ELSE                       '25-36 mo'
END;


-- -----------------------------------------------------------------------------
-- C. DuckDB equivalent (uncomment if using DuckDB)
-- -----------------------------------------------------------------------------

/*
-- Create tables in DuckDB from CSVs directly:
CREATE OR REPLACE TABLE mouse_metadata AS
    SELECT * FROM read_csv_auto('data/raw/Mouse_metadata.csv', header=true);

CREATE OR REPLACE TABLE study_results AS
    SELECT * FROM read_csv_auto('data/raw/Study_results.csv', header=true);

CREATE OR REPLACE TABLE mouse_summary AS
    SELECT * FROM read_csv_auto('data/processed/mouse_summary.csv', header=true);
*/


-- -----------------------------------------------------------------------------
-- D. Verification row counts
-- -----------------------------------------------------------------------------

SELECT 'mouse_metadata'  AS table_name, COUNT(*) AS row_count FROM mouse_metadata
UNION ALL
SELECT 'study_results',                 COUNT(*)               FROM study_results
UNION ALL
SELECT 'mouse_summary',                 COUNT(*)               FROM mouse_summary
UNION ALL
SELECT 'drug_regimens',                 COUNT(*)               FROM drug_regimens;
